name: Build SpringBoot App PushOrCreateEvent with Cache

on:
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]
  create:
    tags:
      - "V*"

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      #  maven缓存，不加的话每次都会去重新拉取，会影响速度
      - name: Dependies Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      #  编译打包
      - name: Build with Maven
        run: mvn package -Dmaven.test.skip=true

      - name: Upload files
        # arg info: https://github.com/ncipollo/release-action#release-action
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "target/*.jar"
          tag: V0.1.0
          token: ${{ secrets.GACTION_TOKEN }}


      - name: Send Feishu Message
        run: |
          curl 'https://open.feishu.cn/open-apis/bot/v2/hook/9915ede2-878e-4396-b80f-71b26e55d9be' \
          -H 'Content-Type: application/json' \
          -d '
          {
                "msg_type": "post",
                "content": {
                  "post": {
                    "zh_cn": {
                      "title": "我是一个标题",
                      "content": [
                        [
                          {
                            "tag": "text",
                            "un_escape": true,
                            "text": "第一行&nbsp;:"
                          },
                          {
                            "tag": "a",
                            "text": "超链接",
                            "href": "http://www.feishu.cn"
                          },
                          {
                            "tag": "at",
                            "user_id": "ou_18eac85d35a26f989317ad4f02e8bbbb"
                          }
                        ],
                        [
                          {
                            "tag": "text",
                            "text": "第二行 :"
                          },
                          {
                            "tag": "text",
                            "text": "文本测试"
                          }
                        ],
                        [
                          {
                            "tag": "img",
                            "image_key": "d640eeea-4d2f-4cb3-88d8-c964fab53987",
                            "width": 300,
                            "height": 300
                          }
                        ]
                      ]
                    }
                  }
                }
          }'

      #  登录Docker  Hub
#      - name: Login to  Docker  Hub
#        uses: docker/login-action@v1
#        with:
#          username: ${{  secrets.DOCKER_HUB_USERNAME  }}
#          password: ${{  secrets.DOCKER_HUB_ACCESS_TOKEN  }}
#            - name: Set  up  Docker  Buildx
#                id: buildx
#                uses: docker/setup-buildx-action@v1


      #  build  镜像并push到中央仓库中
#      - name: Build and push
#        id: docker_build
#        uses: docker/build-push-action@v2
#        with:
#          context: ./
#          file: ./Dockerfile
#          push: true
#          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/imageName:latest


      #  push后，用ssh连接服务器执行脚本
#      - name: SSH
#        uses: fifsky/ssh-action@master
#        with:
#          command: |
#            sh  start.sh
#          host: ${{  secrets.HOST  }}
#          user: ${{  secrets.USER  }}
#          key: ${{  secrets.PRIVATE_KEY}}